### ISSUE TITLE
Enhancement: make 2FA settings configurable by non-admin users as well

### ISSUE THREAD

**Issue by snevas** [ScottPeterJohnson/purelymail-issues#117] opened 2022-05-07 12:54 UTC
If you want to setup a mailbox for a family member, you now need to do that together with them. Also whenever they change phones and need a new app password.

**Comment by ScottPeterJohnson** [comment] 2022-05-13 11:06
Duplicate of #98

**Closed as completed by ScottPeterJohnson** 2022-05-13 11:06 UTC
