### ISSUE TITLE
vcard encoding issue (DAVx5, vdirsyncer, thunderbird)

### ISSUE THREAD

**Issue by ichernev** [ScottPeterJohnson/purelymail-issues#147] opened 2022-11-19 19:44 UTC
I have a contact with `ö` letter in their name. When I edit the contact (thunderbird, vdirsyncer, android via DAVx5) and sync, I get two `\xef\xbf\xbd` (U+FFFD) characters (replacement character) back in its place. If I look via the web contacts UI, then the character is correct.

So it seems like uploading the data works, viewing it on the web works, but when I download it the server always answers with `U+FFFD` for each byte outside ASCII. I verified by patching vdirsyncer (a python lib with carddav support) that you return XML with utf-8 in the header, but the  `U+FFFD` character inside.

**Comment by alexandergeiler** [comment] 2023-01-04 07:55
The same for me.
I have some weird characters in my Android address book:
![contact-android](https://user-images.githubusercontent.com/4689177/210508402-718779cf-caa1-4d91-a6b1-22f5bef34bf0.jpg)

But if I check them in the web adressbook from purelymail it looks correct:
![contact-web-adressbook](https://user-images.githubusercontent.com/4689177/210508407-6348937a-ff3d-4182-ba27-a2ba295d3648.png)

That are "german" special characters like äöü ÄÖÜ ß

**Comment by alexandergeiler** [comment] 2023-03-27 09:41
Do you need anything further ? The issue still exist...

**Comment by alexandergeiler** [comment] 2023-04-06 13:00
may be this helps:
https://www.ralf-lang.de/2021/01/27/davx5-caldav-may-break-with-unicode-symbols-in-horde-kronolith-syncs/

This is my DAXx5 log if I add a new contact with a "ö" in it´s name

2023-04-06 15:04:48 15534 [HttpClient] Accept-Language: de-DE, de;q=0.7, *;q=0.5
2023-04-06 15:04:48 15534 [HttpClient] Content-Type: application/xml; charset=utf-8
2023-04-06 15:04:48 15534 [HttpClient] Content-Length: 350
2023-04-06 15:04:48 15534 [HttpClient] Host: purelymail.com
2023-04-06 15:04:48 15534 [HttpClient] Connection: Keep-Alive
2023-04-06 15:04:48 15534 [HttpClient] Accept-Encoding: gzip
2023-04-06 15:04:48 15534 [HttpClient]
2023-04-06 15:04:48 15534 [HttpClient] <?xml version='1.0' encoding='UTF-8' ?><CARD:addressbook-multiget xmlns="DAV:" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><getcontenttype /><getetag /><CARD:address-data content-type="text/vcard" version="4.0" /></prop><href>/webdav/7091/carddav/default/sabre-vobject-69b9fc72-633b-4db5-8a9c-515316275b0c.vcf</href></CARD:addressbook-multiget> 
2023-04-06 15:04:48 15534 [HttpClient] --> END REPORT (350-byte body) 
2023-04-06 15:04:48 15534 [at.bitfire.dav4jvm.BasicDigestAuthHandler] Adding Basic authorization header for https://purelymail.com/webdav/7091/carddav/default/ 
2023-04-06 15:04:48 15534 [HttpClient] <-- 207 Multi-Status https://purelymail.com/webdav/7091/carddav/default/ (230ms) 
2023-04-06 15:04:48 15534 [HttpClient] Date: Thu, 06 Apr 2023 13:04:48 GMT 
2023-04-06 15:04:48 15534 [HttpClient] Content-Type: application/xml 
2023-04-06 15:04:48 15534 [HttpClient] Transfer-Encoding: chunked 
2023-04-06 15:04:48 15534 [HttpClient] 
2023-04-06 15:04:48 15534 [HttpClient] <?xml version="1.0" encoding="UTF-8"?> <multistatus xmlns="DAV:"><response><href>https://purelymail.com/webdav/7091/carddav/default/sabre-vobject-69b9fc72-633b-4db5-8a9c-515316275b0c.vcf</href><propstat><prop><getcontenttype>text/vcard; charset=utf-8</getcontenttype><getetag>"30a3e0fa98ea349a70c9fd4c5996a3fe32889ac8d542de2eade6a48ccdbaeb3ad2001252c3ee2c9a4b0d75e28d177bfd0d08fc8a7a735f4363d9984a898ec60a"</getetag><address-data xmlns="urn:ietf:params:xml:ns:carddav">BEGIN:VCARD&#x0D; VERSION:4.0&#x0D; PRODID:ez-vcard 0.12.0&#x0D; UID:sabre-vobject-69b9fc72-633b-4db5-8a9c-515316275b0c&#x0D; REV:
20230406T130438Z&#x0D; N:**Test;Testmitï¿½ï¿½;;;&#x0D; FN:Testmitï¿½ï¿½ Test&#x0D**; END:VCARD&#x0D; </address-data></prop><status>HTTP/1.1 200 OK</status></propstat></response></multis

See contact in the web portal:
![2023-04-06 15_13_19-Purely Mail __ Kontakte _ https___inbox purelymail com_ – Mozilla Firefox](https://user-images.githubusercontent.com/4689177/230389396-e8c515a0-5fb3-4b66-b1d5-55ff7d5af90d.png)

**Comment by ScottPeterJohnson** [comment] 2023-04-07 13:16
Sorry if it takes me a while to get to things! 
I've actually just never had luck replicating this one. I tried to get the issue to happen with both Thunderbird and Dav5x, and it just stubbornly doesn't.
@alexandergeiler If you could give me the URL of an existing contact with the issue from the HTTP logs, that might help. You posted `https://purelymail.com/webdav/7091/carddav/default/sabre-vobject-69b9fc72-633b-4db5-8a9c-515316275b0c.vcf` above but you appear to have already deleted that one.

**Comment by alexandergeiler** [comment] 2023-04-13 09:02
Hi Scott,
yes, I deleted it already :-)
I created a new contact:
2023-04-13 10:51:35 38972 [HttpClient]
2023-04-13 10:51:35 38972 [HttpClient] <?xml version="1.0" encoding="UTF-8"?>
<multistatus xmlns="DAV:"><response><href>https://purelymail.com/webdav/7091/carddav/default/sabre-vobject-7b09cc13-cfe9-4c91-a143-e81821bf3acf.vcf</href><propstat><prop><getcontenttype>text/vcard; charset=utf-8</getcontenttype><getetag>"75adf606d5438bb60edcb72db31d93cf003a10292b0d99b9a6102dd32e715b5dacfd129a518903b6f2cd3c52019af34387af176592a6a907b9787c1a1942c3f5"</getetag><address-data xmlns="urn:ietf:params:xml:ns:carddav">BEGIN:VCARD&#x0D;
VERSION:4.0&#x0D;
PRODID:ez-vcard 0.12.0&#x0D;
UID:sabre-vobject-7b09cc13-cfe9-4c91-a143-e81821bf3acf&#x0D;
REV:20230413T085109Z&#x0D;
N:LastNameTest;NewTest������ForPurely;;;&#x0D;
FN:NewTest������ForPurely LastNameTest&#x0D;
END:VCARD&#x0D;
</address-data></prop><status>HTTP/1.1 200 OK</status></propstat></response></multistatus>

2023-04-13 10:51:35 38972 [HttpClient] <-- END HTTP (847-byte body)
2023-04-13 10:51:35 38972 [syncadapter.ContactsSyncManager] Processing CardDAV resource sabre-vobject-7b09cc13-cfe9-4c91-a143-e81821bf3acf.vcf
2023-04-13 10:51:35 38972 [syncadapter.ContactsSyncManager] Creating local contact
    PARAMETER #0 = at.bitfire.vcard4android.Contact@478cd9[addresses=[],anniversary=<null>,birthDay=<null>,categories=[],customDates=[],displayName=NewTest������ForPurely LastNameTest,emails=[],familyName=LastNameTest,givenName=NewTest������ForPurely,group=false,impps=[],jobDescription=<null>,jobTitle=<null>,members=[],middleName=<null>,nickName=<null>,note=<null>,organization=<null>,phoneNumbers=[],phoneticFamilyName=<null>,phoneticGivenName=<null>,phoneticMiddleName=<null>,prefix=<null>,relations=[],suffix=<null>,uid=sabre-vobject-7b09cc13-cfe9-4c91-a143-e81821bf3acf,unknownProperties=<null>,urls=[]]
2023-04-13 10:51:35 38972 [BatchOperation] Committing 2 operations:

**Comment by hxueh** [comment] 2023-05-13 18:40
Hi Scott, I have also encounter this issue. DAVx5 and macOS contacts.app, too.
BTW I am using Chinese charcater.

**Comment by ScottPeterJohnson** [comment] 2023-05-17 09:06
I _maybe_ deployed a fix for this.
I'm still unable to replicate; I even went so far as to set up a test with the exact library Dav5x uses.
I did notice that the HTTP header Content-Type we were returning was "application/xml" and not "application/xml; charset=utf-8". Now of course WebDAV is always UTF-8 encoded and the XML also says it's utf-8 encoded, but some libraries might start decoding the body in ISO-8859-1 or some other system default instead based purely on the Content-Type. So now that all requests include the "charset=utf-8" in Content-Type... maybe that was the issue?
It doesn't wholly make sense to me, because I scoured the Dav5x source code and it always defaults to UTF-8. But who knows?
Any confirmation that the issue is still there would be appreciated.

**Comment by alexandergeiler** [comment] 2023-05-17 12:08
Problem still exist.

**Comment by ScottPeterJohnson** [comment] 2023-05-23 10:28
This should now be fixed! I finally got it to replicate; turns out it only happened in production, so all of my attempts to replicate on dev were frustratingly useless. And it only happened on production because production differed from dev on default charset encoders only apparently used in the XML library used to encode the CardDAV response.
I think any cards that were displaying incorrectly should sync correctly now, but if dav5x wrote them back they would've corrupted the unicode characters.

**Closed as completed by ScottPeterJohnson** 2023-05-23 10:28 UTC

**Comment by alexandergeiler** [comment] 2023-05-23 11:18
Works flawlessly. (had to stop the synchronization via dav5x once).
